services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=CaffeineCrafter
    ports:
      - '5432:5432'
    # Mount at parent dir so pg_upgrade works when upgrading image (see docker-library/postgres#37)
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
